# src/modelling/transformations.py
import logging

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F

# Configure logging for 'Shift-Left' visibility
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


class LakehouseTransformer:
    def __init__(self, spark: SparkSession) -> None:
        self.spark: SparkSession = spark
        self.catalog: str = "local"
        self.db: str = "silver"
        self.ns: str = f"{self.catalog}.{self.db}"
        # Path to the verified Golden Mapping generated by your notebook
        self.gov_path: str = "s3a://lakehouse/governance/player_mapping.parquet"

    def init_silver_layer(self) -> None:
        """Initialise the Silver namespace in the Iceberg catalog."""
        self.spark.sql(f"CREATE NAMESPACE IF NOT EXISTS {self.catalog}.{self.db}")

    def _get_resolved_source(self, bronze_path: str, source_name_col: str) -> DataFrame:
        """
        Loads bronze data and joins it with the Golden Mapping via Broadcast Join.
        Logs 'Governance Gaps' if players are missing from the mapping.
        """
        try:
            raw_df: DataFrame = self.spark.read.parquet(bronze_path)
            mapping_df: DataFrame = self.spark.read.parquet(self.gov_path)
        except Exception as e:
            msg = f"❌ Transformation failed: Missing source or governance file. {e}"
            raise FileNotFoundError(msg)

        # Standardise the join
        resolved_df = raw_df.join(
            F.broadcast(mapping_df),
            raw_df[source_name_col] == mapping_df["understat_name"],
            how="inner",
        )

        # SHIFT-LEFT LOGGING: Detect if new players were dropped due to missing mapping
        raw_count = raw_df.count()
        resolved_count = resolved_df.count()
        if raw_count > resolved_count:
            logger.warning(
                f"⚠️ GOVERNANCE GAP: {raw_count - resolved_count} records dropped in {bronze_path}. "
                "Open player_resolution.ipynb to update the Golden Mapping."
            )

        return resolved_df.withColumn("player_id", F.md5(F.col("understat_name"))).withColumn(
            "team_id", F.md5(F.col("team_name"))
        )

    def upsert_dim_teams(self) -> None:
        """SCD Type 1 (Overwrite) for Teams."""
        raw_df: DataFrame = self.spark.read.parquet(
            "s3a://lakehouse/bronze/understat_league.parquet"
        )

        # 1. CLEAN & HASH: Use trim() to prevent whitespace-driven hash mismatches
        # and distinct() to ensure we aren't merging duplicates from the source itself
        teams_df: DataFrame = raw_df.select(
            F.md5(F.trim(F.col("title"))).alias("team_id"),
            F.trim(F.col("title")).alias("team_name"),
            F.current_timestamp().alias("updated_at"),
        ).distinct()

        teams_df.createOrReplaceTempView("source_teams")

        self.spark.sql(f"""
            CREATE TABLE IF NOT EXISTS {self.ns}.dim_teams (
                team_id STRING, team_name STRING, updated_at TIMESTAMP
            ) USING iceberg
        """)

        # 2. IDEMPOTENT MERGE: Explicitly map columns to avoid schema drift issues
        self.spark.sql(f"""
            MERGE INTO {self.ns}.dim_teams t
            USING source_teams s 
            ON t.team_id = s.team_id
            WHEN MATCHED THEN 
                UPDATE SET t.team_name = s.team_name, t.updated_at = s.updated_at
            WHEN NOT MATCHED THEN 
                INSERT (team_id, team_name, updated_at) 
                VALUES (s.team_id, s.team_name, s.updated_at)
        """)

    def upsert_dim_players_scd2(self) -> None:
        """SCD Type 2 for Players. Tracks injury status history."""
        incoming_df: DataFrame = self._get_resolved_source(
            bronze_path="s3a://lakehouse/bronze/premier_injuries.parquet", source_name_col="Player"
        ).select(
            "player_id",
            F.col("understat_name").alias("player_name"),
            "team_name",
            F.col("Reason").alias("injury_status"),
            F.current_timestamp().alias("effective_from"),
            F.lit(None).cast("timestamp").alias("effective_to"),
            F.lit(True).alias("is_current"),
        )

        self.spark.sql(f"""
            CREATE TABLE IF NOT EXISTS {self.ns}.dim_players (
                player_id STRING, player_name STRING, team_name STRING, 
                injury_status STRING, effective_from TIMESTAMP, 
                effective_to TIMESTAMP, is_current BOOLEAN
            ) USING iceberg PARTITIONED BY (is_current)
        """)

        incoming_df.createOrReplaceTempView("incoming_players")

        # Step 1: Expire old versions where status or team has changed
        self.spark.sql(f"""
            MERGE INTO {self.ns}.dim_players t
            USING incoming_players s ON t.player_id = s.player_id AND t.is_current = true
            WHEN MATCHED AND (t.team_name <> s.team_name OR t.injury_status <> s.injury_status)
            THEN UPDATE SET t.effective_to = s.effective_from, t.is_current = false
        """)

        # Step 2: Insert the latest versions for new or recently changed players
        new_records = incoming_df.alias("s").join(
            self.spark.table(f"{self.ns}.dim_players").alias("t"),
            (F.col("s.player_id") == F.col("t.player_id")) & (F.col("t.is_current")),
            "left_anti",
        )
        new_records.writeTo(f"{self.ns}.dim_players").append()

    def write_fact_match_stats(self) -> None:
        """3NF Fact Table linking players/teams to xG metrics."""
        resolved_df: DataFrame = self._get_resolved_source(
            bronze_path="s3a://lakehouse/bronze/understat_league.parquet", source_name_col="title"
        )

        fact_df: DataFrame = resolved_df.select(
            "player_id",
            "team_id",
            F.col("xg").cast("double").alias("xg"),
            F.col("goals").cast("int").alias("actual_goals"),
            F.current_date().alias("snapshot_date"),
        )

        self.spark.sql(f"""
            CREATE TABLE IF NOT EXISTS {self.ns}.fact_match_stats (
                player_id STRING, team_id STRING, xg DOUBLE, 
                actual_goals INT, snapshot_date DATE
            ) USING iceberg PARTITIONED BY (snapshot_date)
        """)

        fact_df.writeTo(f"{self.ns}.fact_match_stats").append()


def run_silver_layer() -> None:
    """Spark entry point for Silver transformations."""
    spark: SparkSession = SparkSession.builder.getOrCreate()
    transformer = LakehouseTransformer(spark)
    transformer.init_silver_layer()
    transformer.upsert_dim_teams()
    transformer.upsert_dim_players_scd2()


def run_gold_layer() -> None:
    """Spark entry point for Gold curation."""
    spark: SparkSession = SparkSession.builder.getOrCreate()
    transformer = LakehouseTransformer(spark)
    transformer.write_fact_match_stats()


if __name__ == "__main__":
    run_silver_layer()
    run_gold_layer()
